# {{ cookiecutter.project_name }} vagrant configuration
required_plugins = [
  "vagrant-hostmanager",
  "vagrant-timezone"
]

nodes = [
  { :hostname => '{{ cookiecutter.project_name|replace('_', '-') }}1', :ip => '{{ cookiecutter.private_network }}', :box => 'bento/ubuntu-14.04', :ram => {{ cookiecutter.memory }}, :cpus => {{ cookiecutter.cpus }}},
]

Vagrant.configure("2") do |config|
  required_plugins.each do |plugin|
    if not Vagrant.has_plugin?(plugin)
      raise "Install required plugin: #{plugin} `vagrant plugin install #{plugin}`"
    end
  end

  config.ssh.insert_key = false
  config.timezone.value = :host
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.include_offline = true

  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end
  config.vm.provision "shell", inline: $provision_shell_script

  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = node[:box]
      node_config.vm.host_name = node[:hostname]
      node_config.vm.network :private_network, ip: node[:ip]
      node_config.hostmanager.aliases = [node[:hostname] + '.vagrant']
      node_config.vm.provider :virtualbox do |vb|
        vb.memory = node[:ram]
        vb.cpus = node[:cpus]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ['guestproperty', 'set', :id, '/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold', 10000]
      end
      node_config.vm.provider "vmware_fusion" do |vb|
        vb.vmx["memsize"] = node[:ram]
        vb.vmx["numvcpus"] = node[:cpus]
      end
    end
  end
end

$provision_shell_script = <<SCRIPT
echo "Updating apt cache"
apt-get -qy update >/dev/null 2>&1
SCRIPT
